### ISSUE TITLE
Trails without informal tag show informal tag in mouseover

### ISSUE THREAD

**Issue by elevenchars** [osmus/OpenTrailMap#1]
When you mouse over a trail which does not have an `informal` tag set it shows `informal=false` in the tag list. This is not a tag which is present on the object on OSM and might confuse new mappers, since the intended value is `informal=no`

Example on OpenTrailMap
![image](https://github.com/osmus/OpenTrailMap/assets/11055681/740536ba-489e-4706-bb57-122babb4fb20)
Way on OSM:
https://www.openstreetmap.org/way/268153916

**Comment by quincylvania** [comment]
Welcome, @elevenchars. This is an issue with planetiler treating this tag as a boolean when really we want all tags imported as strings. It will be fixed next time the tiles are updated (hopefully soon!) Thanks for reporting.

**Comment by quincylvania** [comment]
This was fixed by doing #4.
