### ISSUE TITLE
Clicking trail ways opens a different trail

### ISSUE THREAD

**Issue by elevenchars** [osmus/OpenTrailMap#3]
Clicking ways sometimes will open the OSM link for an entirely different nearby trail. I haven't been able to identify any particular rhyme or reason behind this.

**Example**:
Click the trail located [here](https://opentrailmap.us/#map=22/30.42997103/-97.79010123)
Way that it opens: [w600439599](https://www.openstreetmap.org/way/600439599)
Expected way: [w30969582](https://www.openstreetmap.org/way/30969582)

![Image from Overpass Turbo showing how far apart the ways are on the map](https://github.com/osmus/OpenTrailMap/assets/11055681/9da3abb5-2cde-444d-9fb4-6e47de346f2a)

This is a specific example, but this happens very often (maybe more often with short ways? Not sure)

**Comment by quincylvania** [comment]
@elevenchars Thanks for reporting. This is an issue with Planetiler merging adjacent ways with identical attributes. Only one ID remains, so that's the one that we're linking to. I have a pending fix for this at https://github.com/ZeLonewolf/planetiler-scripts/pull/6.

**Comment by quincylvania** [comment]
This was fixed by doing #4.

**Comment by quincylvania** [comment]
This was recently fixed. Now, not only does clicking on a path show the exact object in OSM, it includes the entity's current tags and metadata.

 
![Screenshot 2023-11-14 at 12 44 19 AM](https://github.com/osmus/OpenTrailMap/assets/2046746/3efa9519-dcdc-41c8-a860-b257250876ac)
