### ISSUE TITLE
Visualize `fixme` tags

### ISSUE THREAD

**Issue by quincylvania** [osmus/OpenTrailMap#32]
Helps mappers looking for places to improve data.

**Comment by quincylvania** [comment]
Done

**Comment by 1ec5** [comment]
Does this include both `fixme` and `FIXME`? There’s a mapper who’s particularly outspoken about retaining the `FIXME` spelling.

**Comment by quincylvania** [comment]
@1ec5 No, but I'm not against adding `FIXME` too. We could also add `todo` and `TODO`

**Comment by quincylvania** [comment]
Since 1e04976b1ea736f6766955be6d3d983f2be41dbe we support `fixme`, `FIXME`, `todo`, and `TODO` in the same map style.
