### ISSUE TITLE
Contour lines

### ISSUE THREAD

**Issue by quincylvania** [osmus/OpenTrailMap#51]
Any good trail map should show relief somehow. We should find a good open contour line dataset we can host and display on the map. Among other benefits, this will help people map `incline` tags.

**Comment by quincylvania** [comment]
@jake-low You had some good ideas on how to do this. Would you mind elaborating here?

**Comment by jake-low** [comment]
Sure.

Years ago Mapzen released a [global elevation dataset on AWS](https://aws.amazon.com/blogs/publicsector/announcing-terrain-tiles-on-aws-a-qa-with-mapzen/). It's still available there as part of the AWS open data program even though Mapzen is no more. The dataset combines a bunch of different DEMs ([digital elevation models](https://en.wikipedia.org/wiki/Digital_elevation_model)) to create a single dataset that covers most of the planet, using the best available (at the time) data for each region. They created this dataset using a tool they built internally called [joerd](https://github.com/tilezen/joerd).

It's pretty easy to generate hillshade and contour tiles from this data using GDAL tools. Here's an example of a hillshade tile I generated just now:

![hillshade](https://github.com/user-attachments/assets/1014d8e7-4d24-48bf-b73f-0a59e3ce02be)

And here's a contour set (the actual contours are vectors, this image of them is a screenshot from [mapshaper](https://mapshaper.org/)).

<img width="839" alt="image" src="https://github.com/user-attachments/assets/6f63e346-af8b-434a-baa4-b62a22a26ad7">

There's a few details I'm glossing over, briefly:
- the source tiles are 256x256 but you generally want to generate hillshades and contours using more resolution than that, so I used a VRT file to combine the tiles together into a virtual dataset and then read a one-tile region of that at the desired resolution/zoom level.
- contours are GeoJSON but need to be simplified and converted to MVT for use in MapLibre
- the hillshade above has a 1px border artifact, to fix that you'd read a slightly larger region and then trim afterwards

But long story short, with a bit of scripting you could generate two tilesets from this data source: a hillshade raster set and a contour lines vector set. Then you could bundle them up as PMTiles archives, stick them in S3, and serve them with Lambda + CloudFront (which I think is how the vector tiles for this project are already being served). Then you could use them in the map stylesheet.

This would probably only have to be done once (mountains don't changing shape very often, and even when they do, this dataset is no longer being updated). I think it'd be about a day or two of work to write the scripts to generate these tilesets. Generating the tiles would take a few days on a modest server. I don't have a guess ready for what it would cost, but we could do a smallish test region initially to get an estimate for that.
