### ISSUE TITLE
Missing canoe route

### ISSUE THREAD

**Issue by pyrog** [osmus/OpenTrailMap#67]
Node network canoe route [A1-A2](https://knooppuntnet.nl/en/analysis/route/15786932/map?layers=background,canoe,nodes,forward-route,backward-route&position=46.32730038,-0.47389565,17) isn't displayed in OpenTrailMap.

**Comment by quincylvania** [comment]
This is intentional. The waterway segments won't show up unless they have a [`canoe`](https://wiki.openstreetmap.org/wiki/Key:canoe) access tag.

**Comment by pyrog** [comment]
At least in Europe we use route relations 😉

**Comment by quincylvania** [comment]
@pyrog Yes, route relations are important, but access tags are fundamental. Apps need to know "can I use a canoe here".
